services:
  subwoofer:
    build: .
    container_name: subwoofer_bot
    restart: unless-stopped
    network_mode: host
    environment:
      - YTDL_PROXY=socks5://127.0.0.1:40000
    volumes:
      # Mapowanie pliku .env by można było łatwo zmienić token na produkcji bez przebudowy
      - ./.env:/app/.env
      # Logi również wyciągamy na zewnątrz by były łatwo dostępne
      - ./bot.log:/app/bot.log
      # Stan bota (zablokowany kanał muzyczny)
      - ./bot_state.json:/app/bot_state.json
